// Generated by CoffeeScript 1.7.1

/*
  backbone-mongo.js 0.6.0
  Copyright (c) 2013-2014 Vidigami
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
  Source: https://github.com/vidigami/backbone-orm
  Dependencies: Backbone.js and Underscore.js.
 */

(function() {
  var modelEach;

  modelEach = require('./model_each');

  module.exports = function(model_type) {
    model_type.each = function(query, iterator, callback) {
      var _ref;
      if (arguments.length === 2) {
        _ref = [{}, query, iterator], query = _ref[0], iterator = _ref[1], callback = _ref[2];
      }
      return modelEach(model_type, query, iterator, callback);
    };
    return model_type.eachC = function(query, callback, iterator) {
      var _ref;
      if (arguments.length === 2) {
        _ref = [{}, query, callback], query = _ref[0], callback = _ref[1], iterator = _ref[2];
      }
      return modelEach(model_type, query, iterator, callback);
    };
  };

}).call(this);
